let firstName='jessica';
let lastName='zhang';
let age=30;
let dateBirth='0401989';
let address='99 dalhousie';
console.log('first name:' , firstName);
console.log('last name:' , lastName);
console.log('Age:' , age);
console.log('date of birth:' , dateBirth);
console.log('address:' , address);