var firstName='jessica';
var lastName='zhang';
var age=30;
var dateBirth='0401989';
var address='99 dalhousie';
console.log('first name:' , firstName);
console.log('last name:' , lastName);
console.log('Age:' , age);
console.log('date of birth:' , dateBirth);
console.log('address:' , address);